import 'dart:async';
import 'package:uuid/uuid.dart';
import '../../domain/entities/device_data.dart';
import '../../domain/entities/device_entity.dart';
import '../../../emergency/domain/entities/emergency_event.dart';
import 'device_communication_service.dart';

class MockDeviceCommunicationService implements DeviceCommunicationService {
  final _uuid = const Uuid();

  DeviceConnectionState _connectionState = DeviceConnectionState.connected;
  late DeviceData _currentData;
  Timer? _telemetryTimer;

  final _dataController = StreamController<DeviceData>.broadcast();
  final _connectionController =
      StreamController<DeviceConnectionState>.broadcast();
  final _emergencyController = StreamController<EmergencyEvent>.broadcast();

  MockDeviceCommunicationService() {
    _currentData = DeviceData(
      heartRate: 74,
      motionState: MotionState.normalWalking,
      batteryPercentage: 82,
      latitude: 18.52043,
      longitude: 73.85674,
      gpsAccuracy: 4.2,
      gpsStatus: GpsStatus.available,
      networkStatus: NetworkStatus.cellular4G,
      timestamp: DateTime.now(),
    );

    _startPeriodicTelemetry();
  }

  void _startPeriodicTelemetry() {
    _telemetryTimer?.cancel();
    _telemetryTimer = Timer.periodic(const Duration(seconds: 4), (timer) {
      if (_connectionState != DeviceConnectionState.connected) return;

      // Small natural oscillation
      final hrDelta = (timer.tick % 3) - 1; // -1, 0, 1
      final newHr = (_currentData.heartRate ?? 74) + hrDelta;

      _currentData = _currentData.copyWith(
        heartRate: newHr.clamp(60, 100),
        timestamp: DateTime.now(),
      );

      _dataController.add(_currentData);
    });
  }

  @override
  Future<void> connect({String? deviceId}) async {
    _connectionState = DeviceConnectionState.syncing;
    _connectionController.add(_connectionState);

    await Future.delayed(const Duration(milliseconds: 600));

    _connectionState = DeviceConnectionState.connected;
    _connectionController.add(_connectionState);
    _dataController.add(_currentData);
  }

  @override
  Future<void> disconnect() async {
    _connectionState = DeviceConnectionState.disconnected;
    _connectionController.add(_connectionState);
  }

  @override
  Stream<DeviceData> get deviceDataStream => _dataController.stream;

  @override
  Stream<DeviceConnectionState> get connectionStateStream =>
      _connectionController.stream;

  @override
  Stream<EmergencyEvent> get emergencyStream => _emergencyController.stream;

  @override
  Future<DeviceEntity> getDeviceStatus() async {
    return DeviceEntity(
      deviceId: 'wsb_esp32_78a1',
      ownerId: 'usr_owner_demo',
      connectionState: _connectionState,
      currentData: _currentData,
      firmwareVersion: 'v1.4.2-esp32s3',
      lastSeen: DateTime.now(),
    );
  }

  @override
  Future<void> sendCommand(String command, {Map<String, dynamic>? params}) async {
    // Emulate command dispatch (e.g. vibration feedback, cancel watch display alarm)
  }

  // ==========================================
  // HARDWARE SIMULATION CONTROLS FOR TESTING
  // ==========================================

  void simulateWatchConnected() {
    _connectionState = DeviceConnectionState.connected;
    _connectionController.add(_connectionState);
  }

  void simulateWatchDisconnected() {
    _connectionState = DeviceConnectionState.disconnected;
    _connectionController.add(_connectionState);
  }

  void simulateLowBattery() {
    _currentData = _currentData.copyWith(
      batteryPercentage: 9,
      timestamp: DateTime.now(),
    );
    _dataController.add(_currentData);
  }

  void simulateGpsAvailable() {
    _currentData = _currentData.copyWith(
      gpsStatus: GpsStatus.available,
      latitude: 18.52043,
      longitude: 73.85674,
      gpsAccuracy: 3.5,
      timestamp: DateTime.now(),
    );
    _dataController.add(_currentData);
  }

  void simulateGpsUnavailable() {
    _currentData = _currentData.copyWith(
      gpsStatus: GpsStatus.unavailable,
      timestamp: DateTime.now(),
    );
    _dataController.add(_currentData);
  }

  void simulateNormalHeartRate() {
    _currentData = _currentData.copyWith(
      heartRate: 72,
      motionState: MotionState.normalWalking,
      timestamp: DateTime.now(),
    );
    _dataController.add(_currentData);
  }

  void simulateHighHeartRate() {
    _currentData = _currentData.copyWith(
      heartRate: 145,
      timestamp: DateTime.now(),
    );
    _dataController.add(_currentData);
  }

  void simulateAbnormalMotion() {
    _currentData = _currentData.copyWith(
      motionState: MotionState.rapidAcceleration,
      timestamp: DateTime.now(),
    );
    _dataController.add(_currentData);
  }

  /// Triggers a physical Manual SOS button event generated by the wearable
  void simulateManualSos() {
    final event = EmergencyEvent(
      eventId: _uuid.v4(),
      userId: 'usr_owner_demo',
      deviceId: 'wsb_esp32_78a1',
      triggerSource: EmergencyTriggerSource.manualSos,
      status: EmergencyStatus.active,
      latitude: _currentData.latitude,
      longitude: _currentData.longitude,
      accuracyMeters: _currentData.gpsAccuracy,
      locationFreshness: LocationFreshness.live,
      heartRateSnapshot: _currentData.heartRate,
      batterySnapshot: _currentData.batteryPercentage,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );
    _emergencyController.add(event);
  }

  /// Triggers an Automatic Anomaly event (Heart Rate spike + motion shock)
  void simulateAutomaticEmergency() {
    _currentData = _currentData.copyWith(
      heartRate: 142,
      motionState: MotionState.rapidAcceleration,
      timestamp: DateTime.now(),
    );
    _dataController.add(_currentData);

    final event = EmergencyEvent(
      eventId: _uuid.v4(),
      userId: 'usr_owner_demo',
      deviceId: 'wsb_esp32_78a1',
      triggerSource: EmergencyTriggerSource.automaticAnomaly,
      status: EmergencyStatus.detected,
      latitude: _currentData.latitude,
      longitude: _currentData.longitude,
      accuracyMeters: _currentData.gpsAccuracy,
      locationFreshness: LocationFreshness.live,
      heartRateSnapshot: 142,
      batterySnapshot: _currentData.batteryPercentage,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );
    _emergencyController.add(event);
  }

  void simulateEmergencyResolved(String eventId) {
    final event = EmergencyEvent(
      eventId: eventId,
      userId: 'usr_owner_demo',
      deviceId: 'wsb_esp32_78a1',
      triggerSource: EmergencyTriggerSource.manualSos,
      status: EmergencyStatus.resolved,
      latitude: _currentData.latitude,
      longitude: _currentData.longitude,
      accuracyMeters: _currentData.gpsAccuracy,
      locationFreshness: LocationFreshness.live,
      createdAt: DateTime.now().subtract(const Duration(minutes: 5)),
      updatedAt: DateTime.now(),
    );
    _emergencyController.add(event);
  }

  void dispose() {
    _telemetryTimer?.cancel();
    _dataController.close();
    _connectionController.close();
    _emergencyController.close();
  }
}
